ENV_CLOUDFLARE_ZONE_ID: str = 'CLOUDFLARE_ZONE_ID'
ENV_CLOUDFLARE_EMAIL: str = 'CLOUDFLARE_EMAIL'
ENV_CLOUDFLARE_API_KEY: str = 'CLOUDFLARE_API_KEY'

ENV_OVH_ENDPOINT: str = 'OVH_ENDPOINT'
ENV_OVH_APPLICATION_KEY: str = 'OVH_APPLICATION_KEY'
ENV_OVH_APPLICATION_SECRET: str = 'OVH_APPLICATION_SECRET'
ENV_OVH_CONSUMER_KEY: str = 'OVH_CONSUMER_KEY'