name: DNS-UpdaterA

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install venv
        run: make install && make sync

      - name: Execute lint
        run: make lint

      - name: Execute type checking
        run: make type-check